export const FETCH_CHARACTER_START = "FETCH_CHARACTER_START";
export const FETCH_CHARACTER_SUCESS = "FETCH_CHARACTER_SUCESS";
export const FETCH_CHARACTER_FAILURE = "FETCH_CHARACTER_FAILURE";
export const FETCH_SINGLE_CHARACTER_START = "FETCH_SINGLE_CHARACTER_START";
export const FETCH_SINGLE_CHARACTER_SUCESS = "FETCH_SINGLE_CHARACTER_SUCESS";
export const FETCH_SINGLE_CHARACTER_FAILURE = "FETCH_SINGLE_CHARACTER_FAILURE";
